export interface ExerciseTemplate {
  id: string;
  name: string;
  nameEn: string;
  muscle: string;
  description: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  equipment: string[];
  imageUrl?: string;
}

export const EXERCISE_DATABASE: Record<string, ExerciseTemplate[]> = {
  'صدر': [
    {
      id: 'chest-1',
      name: 'ضغط البنش المستوي بالبار',
      nameEn: 'Barbell Bench Press',
      muscle: 'صدر',
      description: 'تمرين أساسي لبناء عضلات الصدر الوسطى والقوة العامة',
      difficulty: 'beginner',
      equipment: ['بار', 'بنش مستوي'],
    },
    {
      id: 'chest-2',
      name: 'ضغط البنش المائل بالدمبل',
      nameEn: 'Incline Dumbbell Press',
      muscle: 'صدر',
      description: 'يستهدف الجزء العلوي من الصدر',
      difficulty: 'beginner',
      equipment: ['دمبل', 'بنش مائل'],
    },
    {
      id: 'chest-3',
      name: 'فتح الصدر بالدمبل',
      nameEn: 'Dumbbell Flyes',
      muscle: 'صدر',
      description: 'تمرين عزل لتوسيع الصدر',
      difficulty: 'intermediate',
      equipment: ['دمبل', 'بنش'],
    },
    {
      id: 'chest-4',
      name: 'الضغط على الكابل',
      nameEn: 'Cable Crossover',
      muscle: 'صدر',
      description: 'تمرين عزل ممتاز للصدر السفلي',
      difficulty: 'intermediate',
      equipment: ['كابل'],
    },
    {
      id: 'chest-5',
      name: 'تمرين الضغط',
      nameEn: 'Push-ups',
      muscle: 'صدر',
      description: 'تمرين وزن الجسم الكلاسيكي',
      difficulty: 'beginner',
      equipment: [],
    },
    {
      id: 'chest-6',
      name: 'ضغط البنش المنخفض',
      nameEn: 'Decline Bench Press',
      muscle: 'صدر',
      description: 'يستهدف الجزء السفلي من الصدر',
      difficulty: 'intermediate',
      equipment: ['بار', 'بنش منخفض'],
    },
  ],
  'ظهر': [
    {
      id: 'back-1',
      name: 'الرفعة المميتة',
      nameEn: 'Deadlift',
      muscle: 'ظهر',
      description: 'تمرين مركب لكامل الظهر والجسم',
      difficulty: 'intermediate',
      equipment: ['بار'],
    },
    {
      id: 'back-2',
      name: 'سحب أمامي عريض',
      nameEn: 'Wide Grip Lat Pulldown',
      muscle: 'ظهر',
      description: 'يستهدف عضلات الظهر العريضة',
      difficulty: 'beginner',
      equipment: ['جهاز سحب'],
    },
    {
      id: 'back-3',
      name: 'تجديف بالبار',
      nameEn: 'Barbell Row',
      muscle: 'ظهر',
      description: 'تمرين أساسي لسمك الظهر',
      difficulty: 'intermediate',
      equipment: ['بار'],
    },
    {
      id: 'back-4',
      name: 'تجديف بالدمبل',
      nameEn: 'Dumbbell Row',
      muscle: 'ظهر',
      description: 'تمرين أحادي الجانب للظهر',
      difficulty: 'beginner',
      equipment: ['دمبل', 'بنش'],
    },
    {
      id: 'back-5',
      name: 'عقلة',
      nameEn: 'Pull-ups',
      muscle: 'ظهر',
      description: 'تمرين وزن الجسم للظهر العلوي',
      difficulty: 'advanced',
      equipment: ['عقلة'],
    },
    {
      id: 'back-6',
      name: 'سحب أرضي بالكابل',
      nameEn: 'Seated Cable Row',
      muscle: 'ظهر',
      description: 'تمرين عزل لوسط الظهر',
      difficulty: 'beginner',
      equipment: ['كابل'],
    },
  ],
  'أكتاف': [
    {
      id: 'shoulders-1',
      name: 'ضغط الكتف بالبار',
      nameEn: 'Military Press',
      muscle: 'أكتاف',
      description: 'تمرين أساسي للأكتاف الأمامية',
      difficulty: 'beginner',
      equipment: ['بار'],
    },
    {
      id: 'shoulders-2',
      name: 'رفرفة جانبي بالدمبل',
      nameEn: 'Lateral Raises',
      muscle: 'أكتاف',
      description: 'يستهدف الكتف الجانبي',
      difficulty: 'beginner',
      equipment: ['دمبل'],
    },
    {
      id: 'shoulders-3',
      name: 'رفرفة خلفي بالدمبل',
      nameEn: 'Rear Delt Flyes',
      muscle: 'أكتاف',
      description: 'يستهدف الكتف الخلفي',
      difficulty: 'intermediate',
      equipment: ['دمبل'],
    },
    {
      id: 'shoulders-4',
      name: 'ضغط أرنولد',
      nameEn: 'Arnold Press',
      muscle: 'أكتاف',
      description: 'تمرين شامل للأكتاف',
      difficulty: 'intermediate',
      equipment: ['دمبل'],
    },
    {
      id: 'shoulders-5',
      name: 'رفع أمامي بالبار',
      nameEn: 'Front Raise',
      muscle: 'أكتاف',
      description: 'يستهدف الكتف الأمامي',
      difficulty: 'beginner',
      equipment: ['بار', 'دمبل'],
    },
  ],
  'أرجل': [
    {
      id: 'legs-1',
      name: 'القرفصاء بالبار',
      nameEn: 'Barbell Squat',
      muscle: 'أرجل',
      description: 'ملك تمارين الأرجل',
      difficulty: 'intermediate',
      equipment: ['بار', 'رف القرفصاء'],
    },
    {
      id: 'legs-2',
      name: 'ضغط الرجل',
      nameEn: 'Leg Press',
      muscle: 'أرجل',
      description: 'تمرين آمن للفخذين',
      difficulty: 'beginner',
      equipment: ['جهاز ضغط الرجل'],
    },
    {
      id: 'legs-3',
      name: 'طعنات بالدمبل',
      nameEn: 'Dumbbell Lunges',
      muscle: 'أرجل',
      description: 'تمرين أحادي الجانب للأرجل',
      difficulty: 'beginner',
      equipment: ['دمبل'],
    },
    {
      id: 'legs-4',
      name: 'رفع السمانة واقفاً',
      nameEn: 'Standing Calf Raise',
      muscle: 'أرجل',
      description: 'يستهدف عضلة السمانة',
      difficulty: 'beginner',
      equipment: ['جهاز السمانة'],
    },
    {
      id: 'legs-5',
      name: 'تمديد الرجل',
      nameEn: 'Leg Extension',
      muscle: 'أرجل',
      description: 'عزل للعضلة الرباعية',
      difficulty: 'beginner',
      equipment: ['جهاز تمديد الرجل'],
    },
    {
      id: 'legs-6',
      name: 'ثني الرجل',
      nameEn: 'Leg Curl',
      muscle: 'أرجل',
      description: 'عزل للعضلة الخلفية',
      difficulty: 'beginner',
      equipment: ['جهاز ثني الرجل'],
    },
  ],
  'بايسبس': [
    {
      id: 'biceps-1',
      name: 'تبديل بالدمبل',
      nameEn: 'Alternating Dumbbell Curl',
      muscle: 'بايسبس',
      description: 'تمرين كلاسيكي للبايسبس',
      difficulty: 'beginner',
      equipment: ['دمبل'],
    },
    {
      id: 'biceps-2',
      name: 'تبديل بالبار',
      nameEn: 'Barbell Curl',
      muscle: 'بايسبس',
      description: 'تمرين أساسي للبايسبس',
      difficulty: 'beginner',
      equipment: ['بار'],
    },
    {
      id: 'biceps-3',
      name: 'تبديل مطرقة',
      nameEn: 'Hammer Curl',
      muscle: 'بايسبس',
      description: 'يستهدف البايسبس والساعد',
      difficulty: 'beginner',
      equipment: ['دمبل'],
    },
    {
      id: 'biceps-4',
      name: 'تبديل على البنش المائل',
      nameEn: 'Incline Dumbbell Curl',
      muscle: 'بايسبس',
      description: 'يستهدف الرأس الطويل للبايسبس',
      difficulty: 'intermediate',
      equipment: ['دمبل', 'بنش مائل'],
    },
    {
      id: 'biceps-5',
      name: 'تبديل بالكابل',
      nameEn: 'Cable Curl',
      muscle: 'بايسبس',
      description: 'توتر مستمر على البايسبس',
      difficulty: 'beginner',
      equipment: ['كابل'],
    },
  ],
  'ترايسبس': [
    {
      id: 'triceps-1',
      name: 'ضغط فرنسي بالبار',
      nameEn: 'Skull Crushers',
      muscle: 'ترايسبس',
      description: 'تمرين عزل للترايسبس',
      difficulty: 'intermediate',
      equipment: ['بار', 'بنش'],
    },
    {
      id: 'triceps-2',
      name: 'سحب الكابل للأسفل',
      nameEn: 'Tricep Pushdown',
      muscle: 'ترايسبس',
      description: 'تمرين عزل بالكابل',
      difficulty: 'beginner',
      equipment: ['كابل'],
    },
    {
      id: 'triceps-3',
      name: 'تمديد الترايسبس بالدمبل',
      nameEn: 'Overhead Dumbbell Extension',
      muscle: 'ترايسبس',
      description: 'يستهدف الرأس الطويل للترايسبس',
      difficulty: 'beginner',
      equipment: ['دمبل'],
    },
    {
      id: 'triceps-4',
      name: 'ضغط ضيق',
      nameEn: 'Close Grip Bench Press',
      muscle: 'ترايسبس',
      description: 'تمرين مركب للترايسبس',
      difficulty: 'intermediate',
      equipment: ['بار', 'بنش'],
    },
    {
      id: 'triceps-5',
      name: 'تمديد الترايسبس بالكابل',
      nameEn: 'Cable Overhead Extension',
      muscle: 'ترايسبس',
      description: 'توتر مستمر على الترايسبس',
      difficulty: 'beginner',
      equipment: ['كابل'],
    },
  ],
  'بطن': [
    {
      id: 'abs-1',
      name: 'كرانش',
      nameEn: 'Crunches',
      muscle: 'بطن',
      description: 'تمرين أساسي للبطن العلوي',
      difficulty: 'beginner',
      equipment: [],
    },
    {
      id: 'abs-2',
      name: 'بلانك',
      nameEn: 'Plank',
      muscle: 'بطن',
      description: 'تمرين ثبات للبطن الكامل',
      difficulty: 'beginner',
      equipment: [],
    },
    {
      id: 'abs-3',
      name: 'رفع الأرجل المعلق',
      nameEn: 'Hanging Leg Raises',
      muscle: 'بطن',
      description: 'يستهدف البطن السفلي',
      difficulty: 'advanced',
      equipment: ['عقلة'],
    },
    {
      id: 'abs-4',
      name: 'دراجة هوائية',
      nameEn: 'Bicycle Crunches',
      muscle: 'بطن',
      description: 'يستهدف البطن والجوانب',
      difficulty: 'beginner',
      equipment: [],
    },
    {
      id: 'abs-5',
      name: 'لف روسي',
      nameEn: 'Russian Twists',
      muscle: 'بطن',
      description: 'يستهدف عضلات الجوانب',
      difficulty: 'intermediate',
      equipment: ['دمبل'],
    },
    {
      id: 'abs-6',
      name: 'رفع الأرجل على الأرض',
      nameEn: 'Leg Raises',
      muscle: 'بطن',
      description: 'يستهدف البطن السفلي',
      difficulty: 'intermediate',
      equipment: [],
    },
  ],
  'ساعد': [
    {
      id: 'forearms-1',
      name: 'لف المعصم بالبار',
      nameEn: 'Wrist Curls',
      muscle: 'ساعد',
      description: 'يستهدف عضلات الساعد الأمامية',
      difficulty: 'beginner',
      equipment: ['بار'],
    },
    {
      id: 'forearms-2',
      name: 'لف المعصم العكسي',
      nameEn: 'Reverse Wrist Curls',
      muscle: 'ساعد',
      description: 'يستهدف عضلات الساعد الخلفية',
      difficulty: 'beginner',
      equipment: ['بار'],
    },
    {
      id: 'forearms-3',
      name: 'مسك الدمبل',
      nameEn: 'Farmer\'s Walk',
      muscle: 'ساعد',
      description: 'تمرين قوة القبضة',
      difficulty: 'beginner',
      equipment: ['دمبل'],
    },
  ],
};

export const getDifficultyLabel = (difficulty: string): string => {
  const labels: Record<string, string> = {
    'beginner': 'مبتدئ',
    'intermediate': 'متوسط',
    'advanced': 'متقدم',
  };
  return labels[difficulty] || difficulty;
};

export const getEquipmentLabel = (equipment: string[]): string => {
  if (equipment.length === 0) return 'وزن الجسم';
  return equipment.join(' • ');
};
